# my-chart/templates/alertmanager-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
spec:
  selector:
    app: my-app
    component: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
