{{- if .Values.deployPrometheus }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    app: prometheus
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
    release: {{ .Release.Name }}
  {{- end }}
