apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    app: prometheus
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.prometheus.server.replicaCount }}
  selector:
    matchLabels:
      app: prometheus
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: prometheus
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: prometheus-server
          image: quay.io/prometheus/prometheus:v2.31.1
          args:
            - --config.file=/etc/config/prometheus.yml
            - --storage.tsdb.path=/data
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: storage-volume
              mountPath: /data
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "prometheus.fullname" . }}
        - name: storage-volume
          emptyDir: {}
