apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels:
    app: my-flask-app
spec:
  containers:
    - name: flask-app-container
      image: brunoauditore/my-flask-app:v2
      ports:
        - containerPort: 5000
#      volumeMounts:
#        - name: flask-app-storage
#          mountPath: /data/
#  volumes:
#    - name: flask-app-storage
#      hostPath:
#        path: /data/
#        type: Directory
