apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-root-app
spec:
  generators:
    - list:
        elements:
          - cluster: cluster2
            url: https://192.168.49.2
          - cluster: cluster3
            url: https://192.168.67.2
  template:
    metadata:
      name: '{{cluster}}-my-root-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/Bohdan-Fedoryshyn-LPNU/ArgoCD.git
        targetRevision: HEAD
        path: '{{cluster}}/my-root-app'
      destination:
        server: '{{url}}'
        namespace: myapp