apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
spec:
  project: default
  source:
    repoURL: https://github.com/Bohdan-Fedoryshyn-LPNU/ArgoCD.git
    targetRevision: HEAD
    path: cluster2/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
        