apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  source:
    repoURL: https://github.com/Bohdan-Fedoryshyn-LPNU/ArgoCD.git
    path: "cluster2/applications"
    targetRevision: HEAD