apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'cluster2-my-app'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      source:
        repoURL: https://github.com/Bohdan-Fedoryshyn-LPNU/ArgoCD.git
        path: "cluster2/applications"
        targetRevision: HEAD
