# values.yaml
defaultNamespace: default
customNamespace: cluster3

only_necessary: false
deployPrometheus: false

userApplication:
  replicaCount: 3
  image:
    repository: brunoauditore/my-flask-app
    tag: v2
  service:
    port: 5000