groups:
  - name: example
    rules:
      - alert: HighCpuUsage
        expr: node_cpu_seconds_total{mode="idle"} < (1 - (0.8 * count without (cpu, mode) (node_cpu_seconds_total{mode="idle"})))
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High CPU usage detected
          description: "CPU usage is above 80% (current value: {{ $value }})"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High memory usage detected
          description: "Memory usage is above 90% (current value: {{ $value }})"