apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-app-project
spec:
  sourceRepos:
  - https://github.com/Bohdan-Fedoryshyn-LPNU/ArgoCD.git
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc