apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: {{ .Values.alertmanager.replicaCount }}
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: {{ .Values.alertmanager.image }}
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: alertmanager-config-volume
              mountPath: /etc/alertmanager
              readOnly: true
      volumes:
        - name: alertmanager-config-volume
          configMap:
            name: alertmanager-config
