# templates/alertmanager-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alertmanagerConfigMap.name }}
data:
  alertmanager.yml: |-
{{ .Files.Get "files/alertmanager.yml" | indent 4 }}