apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: 9093
  selector:
    app: alertmanager