apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-chart-3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brunoauditore/ArgoCD/
    targetRevision: master
    path: Helm/my-chart
    helm:
      valueFiles:
        - cluster3_values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
