prometheus:
  replicaCount: 1
  image: prom/prometheus:v2.26.0
  service:
    type: ClusterIP
    port: 9090

alertmanager:
  replicaCount: 1
  image: prom/alertmanager:v0.21.0
  service:
    type: ClusterIP
    port: 9093

# values.yaml
alertmanagerConfigMap:
  name: alertmanager-config

prometheusConfigMap:
  name: prometheus-config

      
