apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argproj.io
spec:
  destination:
    name: my-app
    namespace: my-app
  source:
    repoURL: https://github.com/Bohdan-Fedoryshyn-LPNU/ArgoCD.git
    path: "prod/applications"
    targetRevision: HEAD